apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: workshop-docs
  namespace: openshift
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: system:image-pusher
  namespace: openshift
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-pusher
subjects:
- kind: ServiceAccount
  name: builder
  namespace: workshop-build
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: workshop-docs-build
  namespace: workshop-build
spec:
  failedBuildsHistoryLimit: 3
  output:
    to:
      kind: ImageStreamTag
      name: workshop-docs:latest
      namespace: openshift
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/na-launch/developer-experience-workshop-docs.git
      ref: main
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Containerfile
      env:
        - name: http_proxy
          value: 'http://notused:3128'
        - name: https_proxy
          value: 'https://notused:3128'
        - name: no_proxy
          value: '*'
    type: Docker
  successfulBuildsHistoryLimit: 3
  triggers:
  - type: ConfigChange
